version: "2"
services:
  backend-php-nginx:
    image: nginx:1.16.1
    volumes:
      - "./config/backend/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - backend-php-api
    networks:
      - shared
    ports:
      - 10080:80
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  backend-php-api:
    image: backend-php-api
    build:
      dockerfile: Dockerfile
      context: ./backend
    volumes:
      - ".env-backend:/laravel/.env"
      - "./config/backend/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf"
    networks:
      - shared
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  backend-redis:
    image: redis:5.0.7-alpine
    ports:
      - "6379:6379"
    networks:
      - shared

  backend-db:
    image: mysql:5.7
    container_name: backend-db
    environment:
      MYSQL_DATABASE: backend
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_PASSWORD: backend
      MYSQL_USER: backend
    volumes:
      - backend-db-data:/var/lib/mysql
    networks:
      - shared

## docker-compose rm backend-db  - if you have problem with db init
volumes:
  backend-db-data:

networks:
  shared:
